# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Start Application with Docker Compose
    init: sh scripts/prebuild.sh # Setup the environment
    command: docker-compose up # Start the application

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Postgres
    description: Expose Port 5432 for the Postgres
    port: 5432
  - name: Imgproxy
    description: Expose Port 8080 for Imgproxy
    port: 8080    
    onOpen: ignore
  - name: NGINX
    description: Expose Port 7001 for NGINX serving Imgproxy
    port: 7001 
    onOpen: ignore
  - name: Companion
    description: Expose Port 3020 for Companion
    port: 3020   
    onOpen: ignore
  - name: Minio API
    description: Expose Port 9000 for Minio API
    port: 9000      
    onOpen: ignore  
  - name: Minio Dashboard
    description: Expose Port 9001 for Minio Console
    port: 9001     
  - name: Mailslurper Dashboard
    description: Expose Port 4436 for Mailslurper Dashboard
    port: 4436  
  - name: Mailslurper Service
    description: Expose Port 4437 for Mailslurper Service
    port: 4437   
    onOpen: ignore
  - name: Kratos Public API
    description: Expose Port 4433 for Kratos Public API
    port: 4433  
    onOpen: ignore      
  - name: Kratos Admin API
    description: Expose Port 4434 for Kratos Admin API
    port: 4434    
    onOpen: ignore
  - name: Keto - Read
    description: Expose Port 4466 for Keto - Read
    port: 4466      
    onOpen: ignore  
  - name: Keto - Write
    description: Expose Port 4467 for Keto - Write
    port: 4467
    onOpen: ignore
  - name: Keto - Metrics
    description: Expose Port 4468 for Keto - Metrics
    port: 4468  
    onOpen: ignore
  - name: Oathkeeper Proxy
    description: Expose Port 4455 for Oathkeeper Poxy
    port: 4455
  - name: Oathkeeper API
    description: Expose Port 4456 for Oathkeeper Poxy
    port: 4456          
    onOpen: ignore     
  - name: Kavach Server
    description: Expose Port 5001 for Kavach Server
    port: 5001          
    onOpen: ignore                      


github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true