FROM node:13.12.0-alpine
WORKDIR /app

# install node modules
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm ci

# copy source files to image and build
COPY . .

RUN npm run build
RUN npm install -g serve

# Primary command to run when the container starts
CMD ["serve", "-s", "build"]