log:
  level: debug
  format: json

serve:
  proxy:
    cors:
      enabled: true
      allowed_origins:
        - "*"
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
      exposed_headers:
        - Content-Type
      allow_credentials: true
      debug: true

errors:
  fallback:
    - json

  handlers:
    redirect:
      enabled: true
      config:
        to: http://127.0.0.1:4455/.factly/kavach/web/auth/login
        when:
          - error:
              - unauthorized
              - forbidden
            request:
              header:
                accept:
                  - text/html
    json:
      enabled: true
      config:
        verbose: true

access_rules:
  repositories:
    - file:///etc/config/oathkeeper/access-rules/kavach-web.json
    - file:///etc/config/oathkeeper/access-rules/kavach-studio.json
    - file:///etc/config/oathkeeper/access-rules/kavach-server.json
    - file:///etc/config/oathkeeper/access-rules/kratos.json
    - file:///etc/config/oathkeeper/access-rules/keto-read.json
    - file:///etc/config/oathkeeper/access-rules/keto-write.json
    - file:///etc/config/oathkeeper/access-rules/keto-metadata.json

authenticators:
  anonymous:
    enabled: true
    config:
      subject: guest

  cookie_session:
    enabled: true
    config:
      check_session_url: http://kratos:4433/sessions/whoami
      preserve_path: true
      extra_from: "@this"
      subject_from: "identity.id"
      only:
        - ory_kratos_session

  noop:
    enabled: true

authorizers:
  allow:
    enabled: true
  keto_engine_acp_ory:
    enabled: true

    config:
      base_url: http://keto:4466/
      required_action: ...
      required_resource: ...
      subject: ...
      flavor: ...

mutators:
  noop:
    enabled: true

  id_token:
    enabled: true
    config:
      issuer_url: http://127.0.0.1:4455/
      jwks_url: file:///etc/config/oathkeeper/id_token.jwks.json
      claims: |
        {
          "session": {{ .Extra | toJson }}
        }

  header:
    enabled: true
    config:
      headers:
        X-Kratos: "{{ print .Subject }}"

  hydrator:
    enabled: true
    config:
      api:
        url: http://kavach-server:8000/users/checker
        retry:
          give_up_after: 2s
          max_delay: 100ms
      cache:
        ttl: 60s
