//Actions
export const ADD_APPLICATION_USER = 'ADD_APPLICATION_USER';
export const ADD_APPLICATION_USERS = 'ADD_APPLICATION_USERS';
export const ADD_APPLICATION_USERS_REQUEST = 'ADD_APPLICATION_USERS_REQUEST';
export const SET_APPLICATION_USERS_LOADING = 'SET_APPLICATION_USERS_LOADING';
export const RESET_APPLICATION_USERS = 'RESET_APPLICATION_USERS';

//API
export const APPLICATION_USERS_API = '/organisations';
