// API
export const POLICY_API = '/policy';

//SPACE POLICY
export const ADD_ORGANISATION_POLICY = 'ADD_ORGANISATION_POLICY';
export const DELETE_ORGANISATION_POLICY = 'DELETE_ORGANISATION_POLICY';

//APPLICATION POLICY
export const ADD_APPLICATION_POLICY = 'ADD_APPLICATION_POLICY';
export const DELETE_APPLICATION_POLICY = 'DELETE_APPLICATION_POLICY';

//SPACE POLICY
export const ADD_SPACE_POLICY = 'ADD_SPACE_POLICY';
export const DELETE_SPACE_POLICY = 'DELETE_SPACE_POLICY';
