//Actions
export const ADD_ORGANIZATION = 'ADD_ORGANIZATION';
export const ADD_ORGANIZATIONS = 'ADD_ORGANIZATIONS';
export const RESET_ORGANIZATIONS = 'RESET_ORGANIZATIONS';
export const SET_ORGANIZATIONS_LOADING = 'SET_ORGANIZATIONS_LOADING';
export const SET_SELECTED_ORGANIZATION = 'SET_SELECTED_ORGANIZATION';
//API
export const ORGANIZATIONS_API = '/organizations';
