# Start fresh from a smaller image
FROM alpine:3.9 
RUN apk add ca-certificates

RUN apk add gcc musl-dev
WORKDIR /app
COPY kavach-server .

# Run the binary program produced by `go install`
ENTRYPOINT ["/app/kavach-server"]
CMD ["serve"]