FROM golang:1.18.3-alpine3.16

WORKDIR /app

COPY . .

RUN apk add gcc musl-dev
RUN go mod download

RUN go install github.com/githubnemo/CompileDaemon@latest

# Following lines provides ability to add WAIT_HOSTS in docker-compose to wait for other hosts to start
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
RUN chmod +x /wait

ENTRYPOINT /wait && CompileDaemon -exclude-dir=.git -exclude-dir=docs --build="go build main.go" --command="./main serve"