import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./redux/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </ReduxProvider>
  );
}
