name: Staging Release CI
on:
  push:
    branches: [spaces]
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Use Go
        uses: actions/setup-go@v2
        id: setup_go
        with:
          go-version: "1.16.2"
      - name: Cache go-modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u deshetti --password-stdin
      - name: Build and push kavach web
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            factly/kavach-web:${{ env.RELEASE_VERSION }}-stag
          context: web
          file: web/Dockerfile.prod
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          file: stag.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
